
name: Build Meson (Procursus Roothide)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-meson:
    runs-on: macos-14
    env:
      CACHE_PATH: ${{ github.workspace }}/__procursus_cache
      XCODE_ROOT: /Applications/Xcode_15.2.app
      MEMO_TARGET: iphoneos-arm64-roothide
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      PATH: /opt/procursus/bin:/opt/procursus/sbin:/usr/bin:/bin:/usr/sbin:/sbin

    steps:
      - name: Checkout Procursus repo
        uses: actions/checkout@v4

      - name: Restore Procursus cache
        uses: actions/cache@v3
        id: procursus-cache
        with:
          path: ${{ env.CACHE_PATH }}
          key: procursus

      - name: Copy cached Procursus if available
        if: steps.procursus-cache.outputs.cache-hit == 'true'
        run: |
          mkdir -p ${{ env.CACHE_PATH }}/procursus/var/cache/apt/archives/partial \
            ${{ env.CACHE_PATH }}/procursus/var/lib/apt/lists/partial
          sudo rsync -aWlHh --inplace ${{ env.CACHE_PATH }}/procursus /opt

      - name: Prepare Procursus tools if not cached
        if: steps.procursus-cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ./build_tools/prepare_github_runner.sh
          sudo bash ./build_tools/prepare_github_runner.sh

      - name: Add Procursus to PATH
        run: |
          echo "/opt/procursus/bin" >> $GITHUB_PATH
          echo "/opt/procursus/sbin" >> $GITHUB_PATH
          echo "CPATH=$CPATH:/opt/procursus/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$LIBRARY_PATH:/opt/procursus/lib" >> $GITHUB_ENV
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Ensure make is linked
        run: |
          if [ ! -e /opt/procursus/bin/make ]; then
            sudo ln -sf /opt/procursus/bin/gmake /opt/procursus/bin/make
          fi

      - name: Checkout libroothide
        uses: actions/checkout@v4
        with:
          repository: 0xyousif/libroothide
          path: libroothide

      - name: Build and install symredirect (libroothide)
        shell: bash
        run: |
          cd libroothide
          chmod +x symredirect-host-build.sh
          bash symredirect-host-build.sh
          echo "✅ symredirect installed successfully"
          symredirect || echo "symredirect test completed"

      - name: Build Meson for iOS target
        run: |
          cd ${{ github.workspace }}
          make -j$(sysctl -n hw.ncpu) meson-package MEMO_TARGET=iphoneos-arm64-roothide NO_PGP=1

      - name: Upload build_work archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_work
          path: ${{ github.workspace }}/build_work/iphoneos-arm64-roothide/
